### ISSUE TITLE
Use gradle to manage dependencies

### ISSUE THREAD

**Issue by ghost** [bpear/ARChon-Packager#3]
Is there a reason why zip4j and systembartint are not pulled from central/jcenter via gradle? Shouldn't...

```
compile "net.lingala.zip4j:zip4j:1.3.2"
compile "com.readystatesoftware.systembartint:systembartint:1.0.4"
```

... work as well? This will ease up maintainance in fdroid, a pure floss app repository.

**Comment by ligi** [comment]
https://github.com/bpear96/Chrome-APK-Packager/pull/2

**Comment by bpear** [comment]
Thanks for pointing this out. ligi pull request was merged! :+1:
